/* Copyright 2026 Crane Valley. All Rights Reserved. */
/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_FRAMEDASH_V1_TELEMETRY_PB_H_INCLUDED
#define PB_FRAMEDASH_V1_TELEMETRY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Source of the telemetry event. */
typedef enum _framedash_v1_TelemetrySource {
    framedash_v1_TelemetrySource_TELEMETRY_SOURCE_UNSPECIFIED = 0,
    framedash_v1_TelemetrySource_TELEMETRY_SOURCE_PLAYER = 1,
    framedash_v1_TelemetrySource_TELEMETRY_SOURCE_AUTOMATED = 2
} framedash_v1_TelemetrySource;

/* Struct definitions */
/* 3D position vector for spatial analytics (heatmaps, player tracking). */
typedef struct _framedash_v1_Vector3 {
    float x;
    float y;
    float z;
} framedash_v1_Vector3;

/* Core telemetry event emitted by game SDKs.
 Each event maps to a single row in the ClickHouse `framedash.events` table. */
typedef struct _framedash_v1_GameTelemetryEvent {
    pb_callback_t event_name;
    /* Unix epoch in microseconds. Stored as DateTime64(6) in ClickHouse. */
    int64_t timestamp_us;
    pb_callback_t session_id;
    /* Explicit player identifier — the only PII the SDK may collect. */
    pb_callback_t player_id;
    bool has_position;
    framedash_v1_Vector3 position;
    pb_callback_t map_id;
    float fps;
    float frame_time_ms;
    int64_t memory_used_bytes;
    float gpu_time_ms;
    /* Free-form string key-value pairs for game-specific context. */
    pb_callback_t attributes;
    /* Free-form numeric metrics for game-specific measurements. */
    pb_callback_t metrics;
    /* Source of the telemetry event. */
    framedash_v1_TelemetrySource source;
    pb_callback_t build_id;
    pb_callback_t platform;
    pb_callback_t engine_version;
    /* Camera orientation in degrees.
 camera_yaw: horizontal rotation (0 = North, clockwise, [0, 360)).
 camera_pitch: vertical rotation (-90 = straight down, +90 = straight up).
 'optional' enables has-field presence tracking — distinguishes
 "not sent by SDK" (absent) from "facing North at level" (0, 0). */
    bool has_camera_yaw;
    float camera_yaw;
    bool has_camera_pitch;
    float camera_pitch;
    /* CPU game thread time in milliseconds (logic, AI, physics).
 0 = not collected (old SDK or unavailable). */
    float game_thread_ms;
    /* CPU render thread time in milliseconds (draw commands, culling).
 0 = not collected (old SDK or unavailable). */
    float render_thread_ms;
} framedash_v1_GameTelemetryEvent;

typedef struct _framedash_v1_GameTelemetryEvent_AttributesEntry {
    pb_callback_t key;
    pb_callback_t value;
} framedash_v1_GameTelemetryEvent_AttributesEntry;

typedef struct _framedash_v1_GameTelemetryEvent_MetricsEntry {
    pb_callback_t key;
    double value;
} framedash_v1_GameTelemetryEvent_MetricsEntry;

/* Batch wrapper sent by SDKs via POST /v1/events.
 api_key and sdk_version are transmitted in HTTP headers (X-API-Key, X-SDK-Version),
 not in the Protobuf payload. */
typedef struct _framedash_v1_TelemetryBatch {
    pb_callback_t events;
} framedash_v1_TelemetryBatch;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _framedash_v1_TelemetrySource_MIN framedash_v1_TelemetrySource_TELEMETRY_SOURCE_UNSPECIFIED
#define _framedash_v1_TelemetrySource_MAX framedash_v1_TelemetrySource_TELEMETRY_SOURCE_AUTOMATED
#define _framedash_v1_TelemetrySource_ARRAYSIZE ((framedash_v1_TelemetrySource)(framedash_v1_TelemetrySource_TELEMETRY_SOURCE_AUTOMATED+1))


#define framedash_v1_GameTelemetryEvent_source_ENUMTYPE framedash_v1_TelemetrySource





/* Initializer values for message structs */
#define framedash_v1_Vector3_init_default        {0, 0, 0}
#define framedash_v1_GameTelemetryEvent_init_default {{{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, framedash_v1_Vector3_init_default, {{NULL}, NULL}, 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, _framedash_v1_TelemetrySource_MIN, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, 0, 0}
#define framedash_v1_GameTelemetryEvent_AttributesEntry_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define framedash_v1_GameTelemetryEvent_MetricsEntry_init_default {{{NULL}, NULL}, 0}
#define framedash_v1_TelemetryBatch_init_default {{{NULL}, NULL}}
#define framedash_v1_Vector3_init_zero           {0, 0, 0}
#define framedash_v1_GameTelemetryEvent_init_zero {{{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, framedash_v1_Vector3_init_zero, {{NULL}, NULL}, 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, _framedash_v1_TelemetrySource_MIN, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, 0, 0}
#define framedash_v1_GameTelemetryEvent_AttributesEntry_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define framedash_v1_GameTelemetryEvent_MetricsEntry_init_zero {{{NULL}, NULL}, 0}
#define framedash_v1_TelemetryBatch_init_zero    {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define framedash_v1_Vector3_x_tag               1
#define framedash_v1_Vector3_y_tag               2
#define framedash_v1_Vector3_z_tag               3
#define framedash_v1_GameTelemetryEvent_event_name_tag 1
#define framedash_v1_GameTelemetryEvent_timestamp_us_tag 2
#define framedash_v1_GameTelemetryEvent_session_id_tag 3
#define framedash_v1_GameTelemetryEvent_player_id_tag 4
#define framedash_v1_GameTelemetryEvent_position_tag 5
#define framedash_v1_GameTelemetryEvent_map_id_tag 6
#define framedash_v1_GameTelemetryEvent_fps_tag  8
#define framedash_v1_GameTelemetryEvent_frame_time_ms_tag 9
#define framedash_v1_GameTelemetryEvent_memory_used_bytes_tag 10
#define framedash_v1_GameTelemetryEvent_gpu_time_ms_tag 11
#define framedash_v1_GameTelemetryEvent_attributes_tag 12
#define framedash_v1_GameTelemetryEvent_metrics_tag 13
#define framedash_v1_GameTelemetryEvent_source_tag 14
#define framedash_v1_GameTelemetryEvent_build_id_tag 15
#define framedash_v1_GameTelemetryEvent_platform_tag 16
#define framedash_v1_GameTelemetryEvent_engine_version_tag 17
#define framedash_v1_GameTelemetryEvent_camera_yaw_tag 18
#define framedash_v1_GameTelemetryEvent_camera_pitch_tag 19
#define framedash_v1_GameTelemetryEvent_game_thread_ms_tag 20
#define framedash_v1_GameTelemetryEvent_render_thread_ms_tag 21
#define framedash_v1_GameTelemetryEvent_AttributesEntry_key_tag 1
#define framedash_v1_GameTelemetryEvent_AttributesEntry_value_tag 2
#define framedash_v1_GameTelemetryEvent_MetricsEntry_key_tag 1
#define framedash_v1_GameTelemetryEvent_MetricsEntry_value_tag 2
#define framedash_v1_TelemetryBatch_events_tag   1

/* Struct field encoding specification for nanopb */
#define framedash_v1_Vector3_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    z,                 3)
#define framedash_v1_Vector3_CALLBACK NULL
#define framedash_v1_Vector3_DEFAULT NULL

#define framedash_v1_GameTelemetryEvent_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   event_name,        1) \
X(a, STATIC,   SINGULAR, INT64,    timestamp_us,      2) \
X(a, CALLBACK, SINGULAR, STRING,   session_id,        3) \
X(a, CALLBACK, SINGULAR, STRING,   player_id,         4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  position,          5) \
X(a, CALLBACK, SINGULAR, STRING,   map_id,            6) \
X(a, STATIC,   SINGULAR, FLOAT,    fps,               8) \
X(a, STATIC,   SINGULAR, FLOAT,    frame_time_ms,     9) \
X(a, STATIC,   SINGULAR, INT64,    memory_used_bytes,  10) \
X(a, STATIC,   SINGULAR, FLOAT,    gpu_time_ms,      11) \
X(a, CALLBACK, REPEATED, MESSAGE,  attributes,       12) \
X(a, CALLBACK, REPEATED, MESSAGE,  metrics,          13) \
X(a, STATIC,   SINGULAR, UENUM,    source,           14) \
X(a, CALLBACK, SINGULAR, STRING,   build_id,         15) \
X(a, CALLBACK, SINGULAR, STRING,   platform,         16) \
X(a, CALLBACK, SINGULAR, STRING,   engine_version,   17) \
X(a, STATIC,   OPTIONAL, FLOAT,    camera_yaw,       18) \
X(a, STATIC,   OPTIONAL, FLOAT,    camera_pitch,     19) \
X(a, STATIC,   SINGULAR, FLOAT,    game_thread_ms,   20) \
X(a, STATIC,   SINGULAR, FLOAT,    render_thread_ms,  21)
#define framedash_v1_GameTelemetryEvent_CALLBACK pb_default_field_callback
#define framedash_v1_GameTelemetryEvent_DEFAULT NULL
#define framedash_v1_GameTelemetryEvent_position_MSGTYPE framedash_v1_Vector3
#define framedash_v1_GameTelemetryEvent_attributes_MSGTYPE framedash_v1_GameTelemetryEvent_AttributesEntry
#define framedash_v1_GameTelemetryEvent_metrics_MSGTYPE framedash_v1_GameTelemetryEvent_MetricsEntry

#define framedash_v1_GameTelemetryEvent_AttributesEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, CALLBACK, SINGULAR, STRING,   value,             2)
#define framedash_v1_GameTelemetryEvent_AttributesEntry_CALLBACK pb_default_field_callback
#define framedash_v1_GameTelemetryEvent_AttributesEntry_DEFAULT NULL

#define framedash_v1_GameTelemetryEvent_MetricsEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   SINGULAR, DOUBLE,   value,             2)
#define framedash_v1_GameTelemetryEvent_MetricsEntry_CALLBACK pb_default_field_callback
#define framedash_v1_GameTelemetryEvent_MetricsEntry_DEFAULT NULL

#define framedash_v1_TelemetryBatch_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  events,            1)
#define framedash_v1_TelemetryBatch_CALLBACK pb_default_field_callback
#define framedash_v1_TelemetryBatch_DEFAULT NULL
#define framedash_v1_TelemetryBatch_events_MSGTYPE framedash_v1_GameTelemetryEvent

extern const pb_msgdesc_t framedash_v1_Vector3_msg;
extern const pb_msgdesc_t framedash_v1_GameTelemetryEvent_msg;
extern const pb_msgdesc_t framedash_v1_GameTelemetryEvent_AttributesEntry_msg;
extern const pb_msgdesc_t framedash_v1_GameTelemetryEvent_MetricsEntry_msg;
extern const pb_msgdesc_t framedash_v1_TelemetryBatch_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define framedash_v1_Vector3_fields &framedash_v1_Vector3_msg
#define framedash_v1_GameTelemetryEvent_fields &framedash_v1_GameTelemetryEvent_msg
#define framedash_v1_GameTelemetryEvent_AttributesEntry_fields &framedash_v1_GameTelemetryEvent_AttributesEntry_msg
#define framedash_v1_GameTelemetryEvent_MetricsEntry_fields &framedash_v1_GameTelemetryEvent_MetricsEntry_msg
#define framedash_v1_TelemetryBatch_fields &framedash_v1_TelemetryBatch_msg

/* Maximum encoded size of messages (where known) */
/* framedash_v1_GameTelemetryEvent_size depends on runtime parameters */
/* framedash_v1_GameTelemetryEvent_AttributesEntry_size depends on runtime parameters */
/* framedash_v1_GameTelemetryEvent_MetricsEntry_size depends on runtime parameters */
/* framedash_v1_TelemetryBatch_size depends on runtime parameters */
#define FRAMEDASH_V1_TELEMETRY_PB_H_MAX_SIZE framedash_v1_Vector3_size
#define framedash_v1_Vector3_size                15

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
