/* Copyright 2026 Crane Valley. All Rights Reserved. */
/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "telemetry.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(framedash_v1_Vector3, framedash_v1_Vector3, AUTO)


PB_BIND(framedash_v1_GameTelemetryEvent, framedash_v1_GameTelemetryEvent, AUTO)


PB_BIND(framedash_v1_GameTelemetryEvent_AttributesEntry, framedash_v1_GameTelemetryEvent_AttributesEntry, AUTO)


PB_BIND(framedash_v1_GameTelemetryEvent_MetricsEntry, framedash_v1_GameTelemetryEvent_MetricsEntry, AUTO)


PB_BIND(framedash_v1_TelemetryBatch, framedash_v1_TelemetryBatch, AUTO)





#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

